(blog) Status update 2020-11-27
puppetlabs/iac pull request #148
Opened 2020-11-26 14:55 UTC by carabasdaniel

2020-11-26 15:01 UTC, sanfrancrisko requested changes

2020-11-26 15:01 UTC, sanfrancrisko commented on _posts/2020-11-27-status-update.md
> +This week we managed to fix a couple of stability issues with the Cloud CI provisioning and finish a successful run with 100 windows machines. You can see the results [here](https://github.com/puppet
nit:
```suggestion
This week we managed to fix a couple of stability issues with the Cloud CI provisioning and finish a successful run with 100 Windows machines. You can see the results [here](https://github.com/puppetlabs/puppetlabs-testing/actions/runs/383528880).
```

2020-11-26 17:43 UTC, sanfrancrisko approved these changes

2020-11-27 14:06 UTC, DavidS approved these changes

2020-11-27 14:07 UTC, merged