(BLOG) Status update for 2021-01-15
puppetlabs/iac pull request #175
Opened 2021-01-14 16:43 UTC by sanfrancrisko

2021-01-14 16:54 UTC, Disha-maker reviewed
Great work @sanfrancrisko

2021-01-14 17:01 UTC, Disha-maker commented
Was tagmail not released this week on Triage day this week, or was it last week @sanfrancrisko. I remember doing a session on tagmail JIRA Ticket with @pmcmaw that's why I asked :)

2021-01-14 17:18 UTC, pmcmaw commented
Tagmail was released 10 days ago, we worked on it 2 weeks ago, it was mentioned in last weeks blog @Disha-maker

2021-01-15 10:08 UTC, DavidS requested changes

2021-01-15 10:08 UTC, DavidS commented on _posts/2021-01-15-status-update.md
> +Although we have over 35 of the IAC supported modules using the service, some of our more complex modules are still not ported.
```suggestion
We now have 35 of 47 the IAC supported [modules](https://puppetlabs.github.io/iac/modules/) using the service, only the most complex modules are still not ported, and will require more investment in supporting their additional needs.
```

2021-01-15 10:11 UTC, DavidS commented on _posts/2021-01-15-status-update.md
> +[DavidSwan][DavidSwan] has been diligently continuing with the effort to remove inappropriate terminology from our code repos.
```suggestion
[David Swan][DavidSwan] has been diligently continuing with the effort to remove inappropriate terminology from our code repos.
```

2021-01-15 10:31 UTC, DavidS approved these changes

2021-01-15 10:31 UTC, merged