(blog) 2021-01-29 status update
puppetlabs/iac pull request #185
Opened 2021-01-28 14:57 UTC by tphoney

2021-01-28 15:13 UTC, sanfrancrisko reviewed
Good job figuring all this out and tracking all of the team's work on your own! 👏

2021-01-28 15:13 UTC, sanfrancrisko commented on _posts/2021-01-29-status-update.md
> +tags:
Just some minor alignment issues with the tags

2021-01-28 15:13 UTC, sanfrancrisko commented on _posts/2021-01-29-status-update.md
> +Hey everyone, its my honour to write my first blogpost for Puppet. Kinda strange in i have done a number of other things for puppet, but never a blogpost. Case in point, my talk about [litmus](https:
```suggestion
Hey everyone, it's my honour to write my first blogpost for Puppet. Kinda strange in [I][TP] have done a number of other things for puppet, but never a blogpost. Case in point, my talk about [litmus](https://www.youtube.com/watch?v=FYfR7ZEGHoE) (available permanently on youtube to make me shudder at my own voice). On to business !!!
```

2021-01-28 15:13 UTC, sanfrancrisko commented on _posts/2021-01-29-status-update.md
> +What i can talk a little about is Danny's work on a new proof of concept. We are an automation company so we are always looking to remove a few steps from our process, this project will enable us to
```suggestion
What I can talk a little about is [Danny's][Danny] work on a new proof of concept. We are an automation company so we are always looking to remove a few steps from our process, this project will enable us to automate some of the manual steps required to release modules. Leaving the the human to only review and click merge on Github.
```

2021-01-28 15:13 UTC, sanfrancrisko commented on _posts/2021-01-29-status-update.md
> +Everyone's favourite topic, paula and michael have hit their first milestone, and are now focusing on the most important part. Documentation and blogposts ! There will also be a rebuild of the DSC mo
```suggestion
Everyone's favourite topic, [Paula][Paula] and [Michael][Michael] have hit their first milestone, and are now focusing on the most important part. Documentation and blogposts ! There will also be a rebuild of the DSC modules to fix a vendored path issue. AND the march to 1.0 is well underway with a real focus on testing.
```

2021-01-28 15:13 UTC, sanfrancrisko commented on _posts/2021-01-29-status-update.md
> +On the community day we normally focus on all the wonderful contributions we recieve in github, but over the past couple of weeks we have started to look at our Jira backlog. There are a lot of ticke
```suggestion
On the community day we normally focus on all the wonderful contributions we receive in Github, but over the past couple of weeks we have started to look at our JIRA backlog. There are a lot of tickets there as you can imagine. We have been categorising them based on the module they are associated with and also closing off tickets that are no longer relevant or that have already been fixed.
```

2021-01-28 15:13 UTC, sanfrancrisko commented on _posts/2021-01-29-status-update.md
> +## Our Open Source Contributors
I like this idea, we should integrate this in to the automated generation, actually 👍 

**EDIT:** Actually, reading this again, this may have been an inadvertent suggestion. I thought this was you calling out all the names on top of the Community Contributions section?

2021-01-28 15:13 UTC, sanfrancrisko commented on _posts/2021-01-29-status-update.md
> +
I should have given you my update for this week too, so I'll do it here:

```suggestion

## Networking Device Support Enhancements

[Ciaran][Ciaran] has been working on enhancing the [cisco_ios](https://github.com/puppetlabs/cisco_ios) module to include two new [Bolt tasks](https://puppet.com/docs/bolt/latest/writing_tasks.html) to backup and restore configurations. The PoC has been proven out and now we're just wrapping up on some final development tasks before moving on to more extensive testing. We are looking to make this as universal as we can across as many Cisco devices as we can and have some exciting developments in the pipeline for better testing against Cisco devices. More details soon...
```

2021-01-28 17:52 UTC, sanfrancrisko requested changes

2021-01-28 17:52 UTC, sanfrancrisko commented on _posts/2021-01-29-status-update.md
> +## Our Open Source Contributors
The contributors on [lines 66-72](https://github.com/puppetlabs/iac/pull/185/files#diff-e8352d965ccd9240ebc2b60fb1cf24eb3febd14d1a035d54be8d7246f3368470R66-R72) won't actually show up here. Sorry, I should have spotted this earlier. 

Something like this perhaps:
```MD
## Our Open Source Contributors

  - [ekohl][ekohl]
  - [e-gris][e-gris]
  - [chillinger][chillinger]
  - [olevole][olevole]
  - [b4ldr][b4ldr]
  - [scotje][scotje]
  - [nmaludy][nmaludy]
```

2021-01-29 09:44 UTC, sheenaajay commented on _posts/2021-01-29-status-update.md
> +
May be we can give the actual numbers of PR and tickets looked on community day.

IAC Team processed 19 community PRs processed (9 tooling, 11modules) also we have looked at 31 module issues.

2021-01-29 09:52 UTC, tphoney commented on _posts/2021-01-29-status-update.md
> +
that information is from the slide sheet ?

2021-01-29 10:00 UTC, sheenaajay commented on _posts/2021-01-29-status-update.md
> +
yeah thats right its from the google sheet.

2021-01-29 10:17 UTC, sanfrancrisko approved these changes
LGTM once the stats for the Community Day are in it. @tphoney if you ping Norm, he may have that compiled already

2021-01-29 10:59 UTC, DavidS commented on _posts/2021-01-29-status-update.md
> +What I can talk a little about is [Danny's][Danny] work on a new proof of concept. We are an automation company so we are always looking to remove a few steps from our process, this project will enab
@carabasdaniel , do you have a link to the work handy, so that folks can have a peek on what's cooking?

2021-01-29 10:59 UTC, DavidS commented on _posts/2021-01-29-status-update.md
> +Everyone's favourite topic, [Paula][Paula] and [Michael][Michael] have hit their first milestone, and are now focusing on the most important part. Documentation and blogposts ! There will also be a r
link `milestone` to https://github.com/puppetlabs/Puppet.Dsc/milestone/3?closed=1 ?

2021-01-29 14:53 UTC, sanfrancrisko approved these changes

2021-01-29 14:53 UTC, merged