(BLOG) Status Update for 2021-03-26
puppetlabs/iac pull request #208
Opened 2021-03-25 11:04 UTC by sanfrancrisko

2021-03-25 16:16 UTC, jpogran requested changes

2021-03-25 16:16 UTC, jpogran commented on _posts/2021-03-26-status-update.md
> +This is made up of [James Porgran][James], [David Armstrong][DavidArmstrong] and [Ciaran McCrisken][Ciaran].
```suggestion
This is made up of [James Pogran][James], [David Armstrong][DavidArmstrong] and [Ciaran McCrisken][Ciaran].
```

2021-03-25 16:16 UTC, jpogran commented on _posts/2021-03-26-status-update.md
> +We are focussing on improving the Puppet Developer Experience and one of the products that is going to get significant investment is the [PDK](https://github.com/puppetlabs/pdk).
```suggestion
The DevX team is focused on improving the developer experience across Puppet Products. One of the first areas of focus that is going to get significant time investment is the [PDK](https://github.com/puppetlabs/pdk).
```

2021-03-25 16:16 UTC, jpogran commented on _posts/2021-03-26-status-update.md
> +A full blog post outlining our remit will be coming soon, but we're excited to announce the start of the DevX Team!
```suggestion
A full blog post outlining our remit will be coming soon, but we're excited to announce the start of the newly reformed Developer Experience Team (DevX)!
```

2021-03-25 16:16 UTC, jpogran commented on _posts/2021-03-26-status-update.md
> +We're trying to keep visibility of our roadmap public in the form of [Github Discussions](https://github.com/puppetlabs/pdk/discussions) in the PDK repo.
```suggestion
To discuss future feature work for the PDK, we are trying out the new Github Discussion board [here](https://github.com/puppetlabs/pdk/discussions). This replaces the previous RFC workflow of the pdk-planning repo. If you see an open discussion for a feature you would like implemented, please upvote or comment on the discussion.
```

2021-03-26 10:16 UTC, Disha-maker approved these changes

2021-03-26 10:16 UTC, merged